import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Luxury Prayer App',
      'current_location': 'Current Location',
      'next_prayer': 'Next Prayer',
      'fajr': 'Fajr',
      'sunrise': 'Sunrise',
      'dhuhr': 'Dhuhr',
      'asr': 'Asr',
      'maghrib': 'Maghrib',
      'isha': 'Isha',
      'none': 'None',
      'welcome_user': 'Welcome User',
      'home': 'Home',
      'qibla': 'Qibla',
      'calendar': 'Calendar',
      'settings': 'Settings',
      'notifications': 'Notifications',
      'calculation_method': 'Calculation Method',
      'theme': 'Theme',
      'language': 'Language',
      'enable_notifications': 'Enable Notifications',
      'select_method': 'Select Method',
      'dark_mode': 'Dark Mode',
      'english': 'English',
      'arabic': 'Arabic',
      'general': 'General',
      'location': 'Location',
      'auto_detect': 'Auto-detect (GPS)',
      'reminders': 'Adhan & Reminders',
      'calculation': 'Calculation',
      'method': 'Method',
      'muslim_world_league': 'Muslim World League',
      'asr_juristic': 'Asr Juristic Method',
      'shafi': 'Shafi (Standard)',
      'appearance': 'Appearance',
      'theme_name': 'Dark Luxury',
      'light_mode': 'Light Mode',
      'system_default': 'System Default',
      'hanafi': 'Hanafi',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'time_format': 'Time Format',
      'twelve_hour': '12-hour',
      'twenty_four_hour': '24-hour',
      'large_text': 'Large Text',
      'always_show_home_cards': 'Always show home cards',
      'tasbih': 'Tasbih',
      'azkar': 'Azkar',
      'names_of_allah': 'Names of Allah',
      'morning_azkar': 'Morning Azkar',
      'evening_azkar': 'Evening Azkar',
      'count': 'Count',
      'reset': 'Reset',
      'completion': 'Completion',
      'prayer_tracker': 'Prayer Tracker',
      'dua': 'Dua & Supplications',
      'qibla_map': 'Qibla Map',
      'fajr_done': 'Fajr Done',
      'dhuhr_done': 'Dhuhr Done',
      'asr_done': 'Asr Done',
      'maghrib_done': 'Maghrib Done',
      'isha_done': 'Isha Done',
      'statistics': 'Statistics',
      'last_7_days': 'Last 7 Days',
      'zakat_calculator': 'Zakat Calculator',
      'islamic_events': 'Islamic Events',
      'missed_prayers': 'Missed Prayers (Qada)',
      'total_assets': 'Total Assets (Cash, Bank)',
      'gold_silver': 'Gold & Silver Value',
      'liabilities': 'Liabilities / Debts',
      'calculate': 'Calculate',
      'zakat_due': 'Zakat Due',
      'nisab_threshold': 'Nisab Threshold',
      'eligible_for_zakat': 'Eligible for Zakat',
      'not_eligible': 'Not Eligible',
      'upcoming_events': 'Upcoming Events',
      'days_left': 'days left',
      'missed_fajr': 'Missed Fajr',
      'missed_dhuhr': 'Missed Dhuhr',
      'missed_asr': 'Missed Asr',
      'missed_maghrib': 'Missed Maghrib',
      'missed_isha': 'Missed Isha',
      'hajj_umrah_guide': 'Hajj & Umrah Guide',
      'quran_radio': 'Quran Radio',
      'widget_customization': 'Widget Customization',
      'vibration': 'Vibration',
      'notification_sound': 'Notification Sound',
      'system_sound': 'System Sound',
      'silent': 'Silent',
      'azan': 'Azan',
      'favorites': 'Favorites',
      'bookmarks_tab': 'Bookmarks',
      'notification_prayer_time': 'Prayer-time alert',
      'notification_pre_prayer': 'Pre-prayer reminder',
      'notification_per_prayer': 'Per-prayer notifications',
      'islamic_events_title': 'Islamic occasions',
      'pre_azan_duration': 'Pre-Azan Reminder',
      'minutes_short': 'min',
      'time_remaining_for': 'Time remaining for',
      'passed': 'passed',
      'ago': 'ago',
      'hour_short': 'h',
      'minute_short': 'm',
      'quran': 'Quran',
      'juz': 'Juz',
      'surah': 'Surah',
      'page': 'Page',
      'search_surah': 'Search Surah...',
      'verses': 'Verses',
      'revelation_mecca': 'Meccan',
      'revelation_medina': 'Medinan',
      'bookmarks': 'Bookmarks',
      'last_read': 'Last Read',
      'previous_surah': 'Previous',
      'next_surah': 'Next',
    },
    'ar': {
      'app_title': 'جنة',
      'current_location': 'الموقع الحالي',
      'next_prayer': 'الصلاة القادمة',
      'fajr': 'الفجر',
      'sunrise': 'الشروق',
      'dhuhr': 'الظهر',
      'asr': 'العصر',
      'maghrib': 'المغرب',
      'isha': 'العشاء',
      'none': 'لا يوجد',
      'welcome_user': 'مرحباً بك',
      'home': 'الرئيسية',
      'qibla': 'القبلة',
      'calendar': 'التقويم',
      'settings': 'الإعدادات',
      'notifications': 'الإشعارات',
      'calculation_method': 'طريقة الحساب',
      'theme': 'المظهر',
      'language': 'اللغة',
      'enable_notifications': 'تفعيل الإشعارات',
      'select_method': 'اختر الطريقة',
      'dark_mode': 'الوضع الليلي',
      'english': 'الإنجليزية',
      'arabic': 'العربية',
      'general': 'عام',
      'location': 'الموقع',
      'auto_detect': 'تحديد تلقائي (GPS)',
      'reminders': 'الأذان والتذكير',
      'calculation': 'الحساب',
      'method': 'الطريقة',
      'muslim_world_league': 'رابطة العالم الإسلامي',
      'asr_juristic': 'مذهب العصر',
      'shafi': 'شافعي (قياسي)',
      'appearance': 'المظهر',
      'theme_name': 'داكن فاخر',
      'light_mode': 'الوضع الفاتح',
      'system_default': 'الوضع الافتراضي للنظام',
      'hanafi': 'حنفي',
      'enabled': 'مفعل',
      'disabled': 'معطل',
      'time_format': 'تنسيق الوقت',
      'twelve_hour': '12 ساعة',
      'twenty_four_hour': '24 ساعة',
      'large_text': 'نص كبير',
      'always_show_home_cards': 'إظهار خيارات الصفحة الرئيسية دائمًا',
      'tasbih': 'المسبحة',
      'azkar': 'الأذكار',
      'names_of_allah': 'أسماء الله الحسنى',
      'morning_azkar': 'أذكار الصباح',
      'evening_azkar': 'أذكار المساء',
      'count': 'العدد',
      'reset': 'إعادة تعيين',
      'completion': 'إتمام',
      'prayer_tracker': 'تعقب الصلوات',
      'dua': 'الأدعية',
      'qibla_map': 'خريطة القبلة',
      'fajr_done': 'صلاة الفجر',
      'dhuhr_done': 'صلاة الظهر',
      'asr_done': 'صلاة العصر',
      'maghrib_done': 'صلاة المغرب',
      'isha_done': 'صلاة العشاء',
      'statistics': 'الإحصائيات',
      'last_7_days': 'آخر 7 أيام',
      'zakat_calculator': 'حاسبة الزكاة',
      'islamic_events': 'المناسبات الإسلامية',
      'missed_prayers': 'قضاء الصلوات',
      'total_assets': 'إجمالي الأصول (نقد، بنك)',
      'gold_silver': 'قيمة الذهب والفضة',
      'liabilities': 'الديون والالتزامات',
      'calculate': 'احسب',
      'zakat_due': 'الزكاة المستحقة',
      'nisab_threshold': 'حد النصاب',
      'eligible_for_zakat': 'تجب عليك الزكاة',
      'not_eligible': 'لا تجب عليك الزكاة',
      'upcoming_events': 'المناسبات القادمة',
      'days_left': 'أيام متبقية',
      'missed_fajr': 'فجر فائت',
      'missed_dhuhr': 'ظهر فائت',
      'missed_asr': 'عصر فائت',
      'missed_maghrib': 'مغرب فائت',
      'missed_isha': 'عشاء فائت',
      'mosques_nearby': 'مساجد قريبة',
      'hajj_umrah_guide': 'دليل الحج والعمرة',
      'quran_radio': 'إذاعة القرآن',
      'widget_customization': 'تخصيص الويدجت',
      'vibration': 'الاهتزاز',
      'notification_sound': 'صوت الإشعار',
      'system_sound': 'صوت النظام',
      'silent': 'صامت',
      'azan': 'أذان',
      'favorites': 'المفضلة',
      'bookmarks_tab': 'الفواصل',
      'notification_prayer_time': 'إشعار وقت الصلاة',
      'notification_pre_prayer': 'تذكير قبل الصلاة',
      'notification_per_prayer': 'إشعارات كل صلاة',
      'islamic_events_title': 'المناسبات الإسلامية',
      'pre_azan_duration': 'وقت التذكير قبل الأذان',
      'minutes_short': 'دقيقة',
      'time_remaining_for': 'الوقت المتبقي لـ',
      'passed': 'مرت',
      'ago': 'منذ',
      'hour_short': 'س',
      'minute_short': 'د',
      'quran': 'القرآن الكريم',
      'juz': 'الجزء',
      'surah': 'سورة',
      'page': 'صفحة',
      'search_surah': 'ابحث عن سورة...',
      'verses': 'آية',
      'revelation_mecca': 'مكية',
      'revelation_medina': 'مدنية',
      'bookmarks': 'الفواصل',
      'last_read': 'آخر قراءة',
      'previous_surah': 'السابقة',
      'next_surah': 'التالية',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ar'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
